<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Data_siswa_model extends CI_Model
{

    public $table = 'data_siswa';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('timestamp', $q);
	$this->db->or_like('ra_md', $q);
	$this->db->or_like('nm_siswa', $q);
	$this->db->or_like('tmpt_lhr', $q);
	$this->db->or_like('ttl', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('nik_siswa', $q);
	$this->db->or_like('sklh_umum', $q);
	$this->db->or_like('kelas_sklh', $q);
	$this->db->or_like('tgl_masuk', $q);
	$this->db->or_like('kelas_mad', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('desa', $q);
	$this->db->or_like('kec', $q);
	$this->db->or_like('kab', $q);
	$this->db->or_like('prov', $q);
	$this->db->or_like('no_kk', $q);
	$this->db->or_like('nm_ayah', $q);
	$this->db->or_like('nik_ayah', $q);
	$this->db->or_like('pend_ayah', $q);
	$this->db->or_like('kerja_ayah', $q);
	$this->db->or_like('nm_ibu', $q);
	$this->db->or_like('nik_ibu', $q);
	$this->db->or_like('pend_ibu', $q);
	$this->db->or_like('kerja_ibu', $q);
	$this->db->or_like('gol_ekonomi', $q);
	$this->db->or_like('status_siswa', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('timestamp', $q);
	$this->db->or_like('ra_md', $q);
	$this->db->or_like('nm_siswa', $q);
	$this->db->or_like('tmpt_lhr', $q);
	$this->db->or_like('ttl', $q);
	$this->db->or_like('jk', $q);
	$this->db->or_like('nik_siswa', $q);
	$this->db->or_like('sklh_umum', $q);
	$this->db->or_like('kelas_sklh', $q);
	$this->db->or_like('tgl_masuk', $q);
	$this->db->or_like('kelas_mad', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('desa', $q);
	$this->db->or_like('kec', $q);
	$this->db->or_like('kab', $q);
	$this->db->or_like('prov', $q);
	$this->db->or_like('no_kk', $q);
	$this->db->or_like('nm_ayah', $q);
	$this->db->or_like('nik_ayah', $q);
	$this->db->or_like('pend_ayah', $q);
	$this->db->or_like('kerja_ayah', $q);
	$this->db->or_like('nm_ibu', $q);
	$this->db->or_like('nik_ibu', $q);
	$this->db->or_like('pend_ibu', $q);
	$this->db->or_like('kerja_ibu', $q);
	$this->db->or_like('gol_ekonomi', $q);
	$this->db->or_like('status_siswa', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Data_siswa_model.php */
/* Location: ./application/models/Data_siswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-21 04:18:02 */
/* http://harviacode.com */